// components/common/Navbar.tsx
import Link from "next/link"

export default () => {
  return (
    <div className="fixed w-full">
      <div className="flex justify-between px-16 py-10 items-center ">
        <h1 className="text-white font-extrabold">rjial</h1>
        <div className="flex justify-between space-x-3 text-white">
          <Link href="/"><div className="py-2 px-4 hover:bg-white/10 rounded-md transition ease-in-out">Home</div></Link>
          <Link href="/about"><div className="py-2 px-4 hover:bg-white/10 rounded-md transition ease-in-out">About</div></Link>
          <Link href="/contact"><div className="py-2 px-4 hover:bg-white/10 rounded-md transition ease-in-out">Contact</div></Link>
        </div>
      </div>
    </div>
  )
}

// components/layout/navbar.vue
<template>
  <nav class="fixed top-0 flex justify-between mx-auto px-24 py-5 w-full">
    <span class="font-bold">rjial</span>
    <div class="flex space-x-5">
    
      <a :href="nav.navLink" v-for="nav in navItem" :key="navItem.indexOf(nav)">{{
        nav.navTitle
      }}</a>
    </div>
  </nav>
</template>

<script lang="ts">
import Vue from "vue";
import { NavItem } from "@/models/Navbar";
export default Vue.extend({
  data: () => {
    return {
      navItem: [new NavItem("Home", "#"), new NavItem("About", "#")] as Array<NavItem>,
    };
  },
});
</script>
